#!/usr/bin/node

var fs=require('fs'), Preprocessor=require('../../../bin/commands/build/Preprocessor');

// https://developer.mozilla.org/en-US/docs/Web/JavaScript/New_in_JavaScript

// https://github.com/monolithed/ECMAScript-6
// Used by all browsers except Firefox >= 25 (String.contains : Firefox 18, Map.prototype.forEach : Firefox 25)
var data='(function(global){'
	+fs.readFileSync('../../../node_modules/springboktools/es6/String.js')+"\n"
	+fs.readFileSync('../../../node_modules/springboktools/es6/Array.js')+"\n"
	+fs.readFileSync('../../../node_modules/springboktools/es6/Map.js')+"\n"
	+fs.readFileSync('../../../node_modules/springboktools/es6/Set.js')+"\n"
	+fs.readFileSync('./es6_internal.js')+"\n"
	+'})(window);';

fs.writeFileSync('./es6.js',Preprocessor({},data,true));

fs.writeFileSync('./oldIe.js',''
	+fs.readFileSync('./es5.js')+"\n"
	+fs.readFileSync('./es6.js')+"\n"
);
